#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include<JoystickDriver.c>

const int up = 0;
const int upLeft = 1;
const int left = 2;
const int downLeft = 3;
const int down = 4;
const int downRight = 5;
const int right = 6;
const int upRight = 7;
const int press = -1;

const int power = 75;
int frontLeftFactor = 0;
int frontRightFactor = 0;
int backLeftFactor = 0;
int backRightFactor = 0;

task main()
{
	//controls: 8-way arrow to move straight in various directions. Left and Right triggers to spin.
	while(true)
	{
		getJoystickSettings(joystick);
		motor[frontLeft] = power * frontLeftFactor;
		motor[frontRight] = power * frontRightFactor;
		motor[backLeft] = power * backLeftFactor;
		motor[backRight] = power * backRightFactor;
		
		switch(joystick.joy1_TopHat)
		{
		case up:
			frontLeftFactor = -1;
			frontRightFactor = 1;
			backLeftFactor = 0;
			backRightFactor = 0;
			break;
			
		case upLeft:
			frontLeftFactor = 0;
			frontRightFactor = 1;
			backLeftFactor = -1;
			backRightFactor = 0;
			break;
			
		case left:
			frontLeftFactor = 1;
			frontRightFactor = 0;
			backLeftFactor = -1;
			backRightFactor = 0;
			break;		
		
		case downLeft:
			frontLeftFactor = -1;
			frontRightFactor = 0;
			backLeftFactor = 0;
			backRightFactor = 1;
			break;
			
		case down:
			frontLeftFactor = 0;
			frontRightFactor = 0;
			backLeftFactor = -1;
			backRightFactor = 1;
			break;
			
		case downRight:
			frontLeftFactor = 0;
			frontRightFactor = -1;
			backLeftFactor = 1;
			backRightFactor = 0;
			break;
			
		case right:
			frontLeftFactor = 0;
			frontRightFactor = -1;
			backLeftFactor = 0;
			backRightFactor = 1;
			break;
			
		case upRight:
			frontLeftFactor = 1;
			frontRightFactor = 0;
			backLeftFactor = 0;
			backRightFactor = -1;
			break;
			
		case press:
			frontLeftFactor = 0;
			frontRightFactor = 0;
			backLeftFactor = 0;
			backRightFactor = 0;
			break;
	}//end switch
	
	if(joy1Btn(6))//right trigger
	{
			frontLeftFactor = 1;
			frontRightFactor = 1;
			backLeftFactor = 1;
			backRightFactor = 1;			
	}
	else if(joy1Btn(5))//lrft trigger
	{
			frontLeftFactor = -1;
			frontRightFactor = -1;
			backLeftFactor = -1;
			backRightFactor = -1;		
	}
	
}//end while loop
}
