#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//driver for joysticks
#include<JoystickDriver.c>
#include<spirit.h>

//constants for directions
const int up = 0;
const int upLeft = 1;
const int left = 2;
const int downLeft = 3;
const int down = 4;
const int downRight = 5;
const int right = 6;
const int upRight = 7;
const int press = -1;

int x1 = joystick.joy1_x1;
int x2 = joystick.joy1_x2;
int y1 = joystick.joy1_y1;

const int power = 75;//motor power
//factors to multiply power by

task main()
{
	displayLogo();
	
	while(true)
	{
		//update joystick
		getJoystickSettings(joystick);
		//set drive motors

		motor[frontLeft] = y1 + x1 + x2;
		motor[frontRight] = -y1 + x1 + x2;
		motor[backLeft] = y1 - x1 + x2;
		motor[backRight] = -y1 - x1 + x2;

}//end while loop
}
